### ISSUE TITLE
LSM303 with Feather Adalogger M0

### ISSUE THREAD

**Issue by dewalex** [adafruit/Adafruit_CircuitPython_LIS2MDL#12]
I'm trying to log accelerometer + magnometer data with a feather M0 adalogger using the LSM303AGR, and I'm not getting past the example script for this library.  I have put all of the adafruit libraries onto the SD card, but I'm still getting a memory error when trying to load this library.  Im running 6.2 CP and have downloaded the library bundle from today (2-18-2021). 

Does this library really take that much space to load or is there a different issue?  Is there any way that I can run the sensor with the adalogger?

sdmount.py:
```
import sys

import adafruit_sdcard
import board
import busio
import digitalio
import storage

# Connect to the card and mount the filesystem.
spi = busio.SPI(board.SCK, board.MOSI, board.MISO)
cs = digitalio.DigitalInOut(board.SD_CS)
sdcard = adafruit_sdcard.SDCard(spi, cs)

vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")
sys.path.append("/sd")
sys.path.append("/sd/lib")
```
code.py:
```
import sdmount

import adafruit_lis2mdl

import time
import board
import busio
import digitalio
import gc

print("start: ",gc.mem_free())


# i2c = busio.I2C(board.SCL, board.SDA)
# sensor = adafruit_lis2mdl.LIS2MDL(i2c)

# Define the onboard LED
LED = digitalio.DigitalInOut(board.D13)
LED.direction = digitalio.Direction.OUTPUT

while True:
    LED.value = True
    time.sleep(0.1)
    print(gc.mem_free())
    LED.value = False
    time.sleep(0.1)

    # mag_x, mag_y, mag_z = sensor.magnetic

    # print("X:{0:10.2f}, Y:{1:10.2f}, Z:{2:10.2f} uT".format(mag_x, mag_y, mag_z))
    # print("")
    time.sleep(1.0)
```

**Comment by ladyada** [comment]
yeah the M0 just doesn't have enough RAM. we recommend bumping up to th nRF52840 or SAMD51!

**Comment by dewalex** [comment]
The M0 was the only one I could find that had the SD capability.  Are there nRF52840 or SAMD51 dataloggers?  

I'm trying to build a gps that has an accelerometer/magnometer, and then put an airlift with it to upload the saved tracks later , so I'll need quite a bit of storage space.  I also bought an oled to go with it, so I'm really wanting to keep it at 4 boards or it will be too big.

**Comment by ladyada** [comment]
the STM32F405 has sd card. for project help plz post in the forum. this isnt a library bug :)
