### ISSUE TITLE
Add a compass example

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_LIS2MDL#2]
This PR in an older lib had the good idea to add a compass example:
https://github.com/adafruit/Adafruit_Python_LSM303/pull/4/files

We should add similar code to this lib

**Comment by FoamyGuy** [comment]
I've got an order that includes these sensors on the way to me now. Once they arrive I will work on bringing these examples into the new libraries

**Comment by FoamyGuy** [comment]
I've started an example script for this here: https://github.com/FoamyGuy/CircuitPython_Compass_Example/blob/master/code.py I've tried it with LIS3MDL and LSMDLH and I do get varying 0-360 heading values depending on how I hold and point the sensor. However I'm not certain exactly how to use it to match up the heading values with cardinal directions.

**Comment by ladyada** [comment]
find north - try pointing the X arrow on the board to north, then Y and then Z, you should see a spike in the numbers

**Comment by FoamyGuy** [comment]
Thank you! I was able to get both sensors coordinating pretty closely to a compass app on a phone. Starting with the X arrow pointing north I adjusted slightly the tilt until it matched 0 heading, then I could hold the sensor steady and rotate and see headings in the same range as the ones reported by the phone.

**Comment by FoamyGuy** [comment]
Looking over this again today I notice a slight difference that I am curious about. In the old PR code we have this inside of the `get_heading()` function:

    magnet_axis_data = self.lsm303_sensor.read_magnetometer()
    return self.vector_2_degrees(magnet_axis_data[0], magnet_axis_data[2])

It seems like this would be using x and z values from the magnetometer. Whereas in the arduino [code from here](https://github.com/adafruit/Adafruit_LIS2MDL/blob/master/examples/compass/compass.ino#L31) we have it like this: 

    float heading = (atan2(event.magnetic.y,event.magnetic.x) * 180) / Pi;

Using x and y values from the magnetometer. 

Do I understand it correctly that either of these would work, the difference would be that you need to hold the sensor in a different position (on a different axis?) when you get your compass heading readings?

If so is there any preference for which is used for the new example code?

**Comment by ladyada** [comment]
x and y are the most common

**Comment by kattni** [comment]
This was completed.
